package modelos;

import java.util.ArrayList;
import java.util.List;

public class ProcedureDivision {

	private List<String> linhaProcedure = new ArrayList<String>();
	private String nomePrograma;
	
	public List<String> getLinhaProcedure() {
		return linhaProcedure;
	}
	
	public void gerarProcedureDivision(String programa){

		this.nomePrograma = programa;
		
		this.linhaProcedure.add("      *================================================================*");
		this.linhaProcedure.add("       PROCEDURE                       DIVISION.");
		this.linhaProcedure.add("      *================================================================*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("      * ROTINA DE PROCEDIMENTOS PRINCIPAIS                             *");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       0000-ROTINA-PRINCIPAL           SECTION.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           PERFORM 1000-INICIALIZAR.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           PERFORM 2000-VERIFICAR-VAZIO.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           PERFORM 3000-PROCESSAR      UNTIL WRK-FS-EARQSEQ");
		this.linhaProcedure.add("                                       EQUAL '10'.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           PERFORM 5000-GRAVACAO-ESTRUTURA-FINAL.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           PERFORM 6000-FINALIZAR.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       0000-99-FIM.                    EXIT.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("      * ROTINA DE PROCEDIMENTOS DE INICIALIZACAO                       *");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       1000-INICIALIZAR                SECTION.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           OPEN INPUT  EARQSEQ");
		this.linhaProcedure.add("                OUTPUT SARQXML");
		this.linhaProcedure.add("                       SRELCTRL.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           MOVE WRK-ABERTURA           TO WRK-OPERACAO.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           PERFORM 1100-TESTAR-FILE-STATUS.");
		this.linhaProcedure.add("           PERFORM 1200-OBTER-DATA-HORA.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       1000-99-FIM.                    EXIT.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("      * ROTINA DE TESTE DE FILE-STATUS                                 *");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       1100-TESTAR-FILE-STATUS         SECTION.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           PERFORM 1110-TESTAR-FS-EARQSEQ.");
		this.linhaProcedure.add("           PERFORM 1120-TESTAR-FS-SARQXML.");
		this.linhaProcedure.add("           PERFORM 1130-TESTAR-FS-SRELCTRL.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       1100-99-FIM.                    EXIT.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("      * TESTAR FILE STATUS DO ARQUIVO EARQSEQ                          *");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       1110-TESTAR-FS-EARQSEQ          SECTION.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           IF  WRK-FS-EARQSEQ          NOT EQUAL '00'");
		this.linhaProcedure.add("               MOVE 'APL'              TO ERR-TIPO-ACESSO");
		this.linhaProcedure.add("               MOVE 'EARQSEQ '         TO WRK-NOME-ARQ");
		this.linhaProcedure.add("               MOVE WRK-FS-EARQSEQ     TO WRK-FILE-STATUS");
		this.linhaProcedure.add("               MOVE WRK-MSG-FS-ERRO    TO ERR-TEXTO");
		this.linhaProcedure.add("               PERFORM 9999-ROTINA-ERRO");
		this.linhaProcedure.add("           END-IF.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       1110-99-FIM.                    EXIT.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("      * TESTAR FILE STATUS DO ARQUIVO SARQXML                          *");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       1120-TESTAR-FS-SARQXML          SECTION.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           IF  WRK-FS-SARQXML          NOT EQUAL '00'");
		this.linhaProcedure.add("               MOVE 'APL'              TO ERR-TIPO-ACESSO");
		this.linhaProcedure.add("               MOVE 'SARQXML '         TO WRK-NOME-ARQ");
		this.linhaProcedure.add("               MOVE WRK-FS-SARQXML     TO WRK-FILE-STATUS");
		this.linhaProcedure.add("               MOVE WRK-MSG-FS-ERRO    TO ERR-TEXTO");
		this.linhaProcedure.add("               PERFORM 9999-ROTINA-ERRO");
		this.linhaProcedure.add("           END-IF.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       1120-99-FIM.                    EXIT.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("      * TESTAR FILE STATUS DO ARQUIVO SRELCTRL                         *");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       1130-TESTAR-FS-SRELCTRL         SECTION.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           IF  WRK-FS-SRELCTRL         NOT EQUAL '00'");
		this.linhaProcedure.add("               MOVE 'APL'              TO ERR-TIPO-ACESSO");
		this.linhaProcedure.add("               MOVE 'SRELCTRL'         TO WRK-NOME-ARQ");
		this.linhaProcedure.add("               MOVE WRK-FS-SRELCTRL    TO WRK-FILE-STATUS");
		this.linhaProcedure.add("               MOVE WRK-MSG-FS-ERRO    TO ERR-TEXTO");
		this.linhaProcedure.add("               PERFORM 9999-ROTINA-ERRO");
		this.linhaProcedure.add("           END-IF.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       1130-99-FIM.                    EXIT.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("      * OBTEM DATA E HORA DO SISTEMA                                   *");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       1200-OBTER-DATA-HORA            SECTION.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           CALL 'BRAD7600'             USING WRK-DATA-HORA.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           MOVE WRK-DIA-7600           TO CB2-DIA.");
		this.linhaProcedure.add("           MOVE WRK-MES-7600           TO CB2-MES.");
		this.linhaProcedure.add("           MOVE WRK-ANO-7600           TO CB2-ANO.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       1200-99-FIM.                    EXIT.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("      * VERIFICAR SE ARQUIVO DE ENTRADA ESTA VAZIO                     *");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       2000-VERIFICAR-VAZIO            SECTION.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           PERFORM 2100-LER-EARQSEQ.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           IF  WRK-FS-EARQSEQ          EQUAL '10'");
		this.linhaProcedure.add("               DISPLAY '******************* " + this.nomePrograma + " ******************'");
		this.linhaProcedure.add("               DISPLAY '*                                             *'");
		this.linhaProcedure.add("               DISPLAY '*            ARQUIVO EARQSEQ  VAZIO           *'");
		this.linhaProcedure.add("               DISPLAY '*                                             *'");
		this.linhaProcedure.add("               DISPLAY '*           PROCESSAMENTO  ENCERRADO          *'");
		this.linhaProcedure.add("               DISPLAY '*                                             *'");
		this.linhaProcedure.add("               DISPLAY '******************* " + this.nomePrograma + " ******************'");
		this.linhaProcedure.add("               PERFORM 6000-FINALIZAR");
		this.linhaProcedure.add("           END-IF.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       2000-99-FIM.                    EXIT.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("      * LEITURA DO ARQUIVO EARQSEQ                                     *");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       2100-LER-EARQSEQ                SECTION.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           READ EARQSEQ                INTO REG-XXXX.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           IF  WRK-FS-EARQSEQ          EQUAL '10'");
		this.linhaProcedure.add("               GO                      TO 2100-99-FIM");
		this.linhaProcedure.add("           END-IF.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           MOVE WRK-LEITURA            TO WRK-OPERACAO.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           PERFORM 1110-TESTAR-FS-EARQSEQ.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           ADD 1                       TO ACU-LIDOS-EARQSEQ.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       2100-99-FIM.                    EXIT.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("      * PROCESSAMENTO PRINCIPAL DO PROGRAMA                            *");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       3000-PROCESSAR                  SECTION.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *          ADEQUAR O PROCESSAMENTO DO PROGRAMA CONFORME          *");
		this.linhaProcedure.add("      *                         REGRAS DE NEGOCIO                      *");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           PERFORM 2100-LER-EARQSEQ.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       3000-99-FIM.                    EXIT.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("      * ROTINA PARA GRAVAR ESTRUTURA FINAL DO ARQUIVO                  *");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       5000-GRAVACAO-ESTRUTURA-FINAL   SECTION.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           .");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       5000-99-FIM.                    EXIT.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("      * PRODEDIMENTOS FINAIS DO PROGRAMA                               *");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       6000-FINALIZAR                  SECTION.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           PERFORM 6100-EMITIR-SRELCTRL.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           CLOSE EARQSEQ");
		this.linhaProcedure.add("                 SARQXML");
		this.linhaProcedure.add("                 SRELCTRL.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           MOVE WRK-FECHAMENTO         TO WRK-OPERACAO.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           PERFORM 1100-TESTAR-FILE-STATUS.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           STOP RUN.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       6000-99-FIM.                    EXIT.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("      * EMITE RELATORIO DE CONTROLE.                                   *");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       6100-EMITIR-SRELCTRL            SECTION.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           MOVE WRK-GRAVACAO           TO WRK-OPERACAO.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           MOVE ACU-LIDOS-EARQSEQ      TO WRK-LT1-LIDOS-EARQSEQ.");
		this.linhaProcedure.add("           MOVE ACU-GRAVA-SARQXML      TO WRK-LT2-GRAVA-SARQXML.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           WRITE FD-SRELCTRL           FROM WRK-CABEC1.");
		this.linhaProcedure.add("           PERFORM 1130-TESTAR-FS-SRELCTRL.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           WRITE FD-SRELCTRL           FROM WRK-CABEC2.");
		this.linhaProcedure.add("           PERFORM 1130-TESTAR-FS-SRELCTRL.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           WRITE FD-SRELCTRL           FROM WRK-LINDET1.");
		this.linhaProcedure.add("           PERFORM 1130-TESTAR-FS-SRELCTRL.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           WRITE FD-SRELCTRL           FROM WRK-CABEC3.");
		this.linhaProcedure.add("           PERFORM 1130-TESTAR-FS-SRELCTRL.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           WRITE FD-SRELCTRL           FROM WRK-LINDET1.");
		this.linhaProcedure.add("           PERFORM 1130-TESTAR-FS-SRELCTRL.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           WRITE FD-SRELCTRL           FROM WRK-CABEC4.");
		this.linhaProcedure.add("           PERFORM 1130-TESTAR-FS-SRELCTRL.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           WRITE FD-SRELCTRL           FROM WRK-LINDET1.");
		this.linhaProcedure.add("           PERFORM 1130-TESTAR-FS-SRELCTRL.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           WRITE FD-SRELCTRL           FROM WRK-LINDET1.");
		this.linhaProcedure.add("           PERFORM 1130-TESTAR-FS-SRELCTRL.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           WRITE FD-SRELCTRL           FROM WRK-LINTOT1.");
		this.linhaProcedure.add("           PERFORM 1130-TESTAR-FS-SRELCTRL.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           WRITE FD-SRELCTRL           FROM WRK-LINTOT2.");
		this.linhaProcedure.add("           PERFORM 1130-TESTAR-FS-SRELCTRL.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       6100-99-FIM.                    EXIT.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("      * ROTINA PARA TRATAMENTOS DE ERROS                               *");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       9999-ROTINA-ERRO                SECTION.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           MOVE '"+ this.nomePrograma +"'             TO ERR-PGM.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           CALL 'BRAD7100'             USING WRK-BATCH");
		this.linhaProcedure.add("                                             ERRO-AREA.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("           GOBACK.");
		this.linhaProcedure.add("");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
		this.linhaProcedure.add("       9999-99-FIM.                    EXIT.");
		this.linhaProcedure.add("      *----------------------------------------------------------------*");
	}
}
